package kontroleri;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;

public class PosjetilacPogledController {
	@FXML
	private Button btnKarte;
	@FXML
	private Button btnPozorista;
	@FXML
	private Button btnOsoblje;
	@FXML
	private Button btnIzloguj;
	@FXML
	private ListView listaTrenutneK;
	@FXML
	private ListView listaPrethodneK;
	@FXML
	private TextField status48;
	@FXML
	private Button btnUpravljajRez;

	// Event Listener on Button[#btnKarte].onAction
	@FXML
	public void prebaciKarte(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPozorista].onAction
	@FXML
	public void prebaciPozorista(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnOsoblje].onAction
	@FXML
	public void prebaciOsoblje(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnIzloguj].onAction
	@FXML
	public void izloguj(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ListView[#listaTrenutneK].onMouseClicked
	@FXML
	public void urediKarte(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnUpravljajRez].onAction
	@FXML
	public void upravljajRezervacijama(ActionEvent event) {
		// TODO Autogenerated
	}
}
