package kontroleri.posjetilac;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;
import kontroleri.PomocniKontroler;
import modeli.OsobljePredstave;
import modeli.Tip;

public class InfoOsobljeController {
	@FXML
	private Button btnKarte;
	@FXML
	private Button btnPozorista;
	@FXML
	private Button btnOsoblje;
	@FXML
	private Button btnIzloguj;
	@FXML
	private Label lblIme;
	@FXML
	private Label lblPrezime;
	@FXML
	private ListView<String> lvUcestvuje;
	@FXML
	private Label lblKategorija;

	// Event Listener on Button[#btnKarte].onAction
		@FXML
		public void prebaciKarte(ActionEvent event) throws IOException {
			PomocniKontroler help = new PomocniKontroler();
			help.kartePogledScena(event);
		}
		// Event Listener on Button[#btnPozorista].onAction
		@FXML
		public void prebaciPozorista(ActionEvent event) throws IOException {
			PomocniKontroler help = new PomocniKontroler();
			help.predstavePogledScena(event);
		}
		// Event Listener on Button[#btnOsoblje].onAction
		@FXML
		public void prebaciOsoblje(ActionEvent event) throws IOException {
			
			PomocniKontroler help = new PomocniKontroler();
			help.prebaciOsoblje(event);
		}
		// Event Listener on Button[#btnIzloguj].onAction
		@FXML
		public void izloguj(ActionEvent event) throws IOException {
			PomocniKontroler help = new PomocniKontroler();
			help.izlogujScena(event);
		}
	// Event Listener on ListView[#lvUcestvuje].onMouseClicked
	@FXML
	public void oOsoblju(MouseEvent event) {
		// TODO Autogenerated
	}
	public void initOsoblje() {
		lblIme.setText(OsobljePredstave.trenutno.getOsobljeID().getIme());
		lblPrezime.setText(OsobljePredstave.trenutno.getOsobljeID().getPrezime());
		lblKategorija.setText(Tip.getString(OsobljePredstave.trenutno.getOsobljeID().getTip()));
		
		lvUcestvuje.getItems().addAll(OsobljePredstave.vratiPredstave(OsobljePredstave.trenutno));
		
	}
}
