package kontroleri.posjetilac;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import kontroleri.PomocniKontroler;
import javafx.scene.control.TableColumn;

public class OsobljePogledController {
	@FXML
	private Button btnKarte;
	@FXML
	private Button btnPozorista;
	@FXML
	private Button btnOsoblje;
	@FXML
	private Button btnIzloguj;
	@FXML
	private TableView tabelaOsoblje;
	@FXML
	private TableColumn tcIme;
	@FXML
	private TableColumn tcPrezime;
	@FXML
	private TableColumn tcPredstave;
	@FXML
	private Button btnGlumac;
	@FXML
	private Button btnReziser;
	@FXML
	private Button btnAutor;
	@FXML
	private Button btnSvoOsoblje;

	// Event Listener on Button[#btnKarte].onAction
	@FXML
	public void prebaciKarte(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.kartePogledScena(event);
	}
	// Event Listener on Button[#btnPozorista].onAction
	@FXML
	public void prebaciPozorista(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.predstavePogledScena(event);
	}
	// Event Listener on Button[#btnOsoblje].onAction
	@FXML
	public void prebaciOsoblje(ActionEvent event) throws IOException {
		
		PomocniKontroler help = new PomocniKontroler();
		help.prebaciOsoblje(event);
	}
	// Event Listener on Button[#btnIzloguj].onAction
	@FXML
	public void izloguj(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.izlogujScena(event);
	}
	
	// Event Listener on Button[#btnGlumac].onAction
	@FXML
	public void glumac(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReziser].onAction
	@FXML
	public void reziser(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnAutor].onAction
	@FXML
	public void autor(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnSvoOsoblje].onAction
	@FXML
	public void svoOsoblje(ActionEvent event) {
		// TODO Autogenerated
	}
}
