package kontroleri.posjetilac;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.input.MouseEvent;
import kontroleri.PomocniKontroler;
import modeli.PosjetilacPozorista;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.Tab;

import javafx.event.Event;

public class PosjetilacPogledController implements Initializable {
	@FXML
	private Button btnKarte;
	@FXML
	private Button btnPozorista;
	@FXML
	private Button btnOsoblje;
	@FXML
	private Button btnIzloguj;
	@FXML
	private ListView<String> lvStatus48;
	@FXML
	private Button btnUpravljajRez;
	@FXML
	private Tab tabTekuce;
	@FXML
	private ListView<String> lvTekuce;
	@FXML
	private Tab tabProtekle;
	@FXML
	private ListView<String> lvProtekle;

	


	// Event Listener on Button[#btnKarte].onAction
	@FXML
	public void prebaciKarte(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.kartePogledScena(event);
	}
	// Event Listener on Button[#btnPozorista].onAction
	@FXML
	public void prebaciPozorista(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.predstavePogledScena(event);
	}
	// Event Listener on Button[#btnOsoblje].onAction
	@FXML
	public void prebaciOsoblje(ActionEvent event) throws IOException {
		
		PomocniKontroler help = new PomocniKontroler();
		help.prebaciOsoblje(event);
	}
	// Event Listener on Button[#btnIzloguj].onAction
	@FXML
	public void izloguj(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.izlogujScena(event);
	}
		// Event Listener on ListView[#listaTrenutneK].onMouseClicked
		@FXML
		public void urediKarte(MouseEvent event) {
			// TODO Autogenerated
		}
		// Event Listener on Button[#btnUpravljajRez].onAction
		@FXML
		public void upravljajRezervacijama(ActionEvent event) {
			// TODO Autogenerated
		}
		public void initPosjetilac() {
			lvTekuce.getItems().addAll(PosjetilacPozorista.vratiMojeTekuceKarte());
			lvProtekle.getItems().addAll(PosjetilacPozorista.vratiMojeProtekleKarte());
			lvStatus48.getItems().addAll((PosjetilacPozorista.vrati48()));
		}
		// Event Listener on Tab[#tabTekuce].onSelectionChanged
		@FXML
		public void popuniTekuceRezervacije(Event event) {
			//lvTekuce.getItems().addAll(PosjetilacPozorista.vratiMojeKarte(pp));
		}
		// Event Listener on Tab[#tabProtekle].onSelectionChanged
		@FXML
		public void popuniProtekle(Event event) {
			// TODO Autogenerated
		}
		@Override
		public void initialize(URL arg0, ResourceBundle arg1) {
			//initPosjetilac();
			
		}
}
