package kontroleri.posjetilac;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.input.MouseEvent;
import kontroleri.PomocniKontroler;
import modeli.IzvodjenjePredstave;
import modeli.Karta;
import modeli.PosjetilacPozorista;
import modeli.Pozoriste;
import modeli.Status;
import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;



public class RezervisiController implements Initializable{
	@FXML
	private Button btnKarte;
	@FXML
	private Button btnPozorista;
	@FXML
	private Button btnOsoblje;
	@FXML
	private Button btnIzloguj;
	@FXML
	private ListView<String> infoRezervacija;
	@FXML
	private Button btnPotvrdiIzmjenu;
	@FXML
	private Spinner<Integer> spnBrojKarata;
	
	private IzvodjenjePredstave ip;
	
	private Karta k;
	
	private int br_sjedista;

	// Event Listener on Button[#btnKarte].onAction
	@FXML
	public void prebaciKarte(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.kartePogledScena(event);
	}
	// Event Listener on Button[#btnPozorista].onAction
	@FXML
	public void prebaciPozorista(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.predstavePogledScena(event);
	}
	// Event Listener on Button[#btnOsoblje].onAction
	@FXML
	public void prebaciOsoblje(ActionEvent event) throws IOException {
		
		PomocniKontroler help = new PomocniKontroler();
		help.prebaciOsoblje(event);
	}
	// Event Listener on Button[#btnIzloguj].onAction
	@FXML
	public void izloguj(ActionEvent event) throws IOException {
		PomocniKontroler help = new PomocniKontroler();
		help.izlogujScena(event);
	}
	// Event Listener on ListView[#infoRezervacija].onMouseClicked
	@FXML
	public void urediKarte(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPotvrdiIzmjenu].onAction
	@FXML
	public void potvrdiIzmjenu(ActionEvent event) {
		
		if(PosjetilacPozorista.trenutni!=null && ip.getPozoriste().brKarataValidan(spnBrojKarata.getValue())==true && ip.datumIstekao(ip)==false)
		{
			
			br_sjedista = ip.getPozoriste().getBrojSjedista();
			k = new Karta(ip.getId(), Status.REZERVISANA_NP, PosjetilacPozorista.trenutni.getId(), spnBrojKarata.getValue());
			Karta.ubaciMe(k);
			ip.umanjiBrojNezauzetih(spnBrojKarata.getValue());
		}
		else
			System.out.println("Izvinjavamo se!");
	}
	
	public void initIzvodjenje(IzvodjenjePredstave 	ip) {
		this.ip = ip;
	}
	
	
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		SpinnerValueFactory<Integer> valueFactory = 

				new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 10);

		valueFactory.setValue(1);
		spnBrojKarata.setValueFactory(valueFactory);

	}
}
